name: Build and publish

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Configure time zone
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Oslo"    

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Write settings.xml
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          servers: '[{"id": "github-fsjava","username": "lovisa-jira","password": "${{secrets.CR_PAT}}"},{"id": "github-lovisatools","username": "lovisa-jira","password": "${{secrets.CR_READ_PAT}}"},{"id": "github-lisens","username": "lovisa-jira","password": "${{secrets.CR_READ_PAT}}"}]'
          repositories: '[{"id": "github-fsjava","url": "https://maven.pkg.github.com/domstolene/fs-java"},{"id": "github-lovisatools","url": "https://maven.pkg.github.com/domstolene/lovisa-tools"},{"id": "central","url": "https://repo1.maven.org/maven2","releases": {"enabled":"true"},"snapshots": {"enabled": "true"}},{"id": "jboss","url": "https://repository.jboss.org/nexus/content/groups/public/","releases": {"enabled": "true"},"snapshots": {"enabled": "true"}}]'
          plugin_repositories: '[{"id": "github-lisens","url": "https://maven.pkg.github.com/domstolene/lisenssjekk"},{"id": "github-lovisatools","url": "https://maven.pkg.github.com/domstolene/lovisa-tools"},{"id": "redhat","url": "https://maven.repository.redhat.com/ga"}]'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots deploy
